buttons:
  - type: led_push_button
    switch_pin: 17
    led_pin: 4
    label: yellow
  - type: led_push_button
    switch_pin: 27
    led_pin: 18
    label: green
  - type: led_push_button
    switch_pin: 23
    led_pin: 22
    label: red
  - type: led_push_button
    switch_pin: 25
    led_pin: 24
    label: blue

servos:
  - type: continuous
    servo_channel: 0
  - type: servo
    servo_channel: 1
  - type: servo
    servo_channel: 14
  - type: servo
    servo_channel: 15
    servo_range: [125, 625]
  - type: servo
    servo_channel: 8
  - type: servo
    servo_channel: 9

display:
  - type: oled
    echo_result: true


