buttons:
  - type: led_push_button
    switch_pin: 17
    led_pin: 4
    label: blue
  - type: led_push_button
    switch_pin: 27
    led_pin: 18
    label: green
  - type: led_push_button
    switch_pin: 23
    led_pin: 22
    label: yellow
  - type: led_push_button
    switch_pin: 25
    led_pin: 24
    label: red

servos:
  - type: continuous
    servo_channel: 0
    label: right_arm
  - type: servo
    servo_channel: 4
    label: head
  - type: servo
    servo_channel: 14
    label: left_shoulder
  - type: servo
    servo_channel: 15
    servo_range: [125, 625]
    label: left_arm

display:
  - type: oled
    echo_result: true


adc:
  spi_clk: 16
  spi_miso: 19
  spi_mosi: 20
  spi_cs: 21
  callback_defs:
    - apin: 2
      type: knob
    - apin: 3
      type: knob
