buttons:
  - type: led_push_button
    switch_pin: 18
    led_pin: 4
  - type: led_push_button
    switch_pin: 27
    led_pin: 17
  - type: led_push_button
    switch_pin: 23
    led_pin: 22
  - type: led_push_button
    switch_pin: 25
    led_pin: 24

servos:
  - type: servo
    servo_channel: 0
  - type: servo
    servo_channel: 1
  - type: servo
    servo_channel: 4
  - type: continuous
    servo_channel: 5
  - type: servo
    servo_channel: 8
  - type: servo
    servo_channel: 9
